### ISSUE TITLE
Asymmetry in format for sector ID

### ISSUE THREAD

**Issue by whyrusleeping** [filecoin-project/go-sectorbuilder#5]
in `SectorSealingStatus` and `StagedSectorMetadata`, sector ID is a uint64. But in `VerifySeal` the caller is expected to turn it into a `[31]byte` somehow. The api should be consistent, and I think the best approach here would be to simply change the sectorID in `VerifySeal` to accept a uint64

**Comment by laser** [comment]
The issue here is that the sector builder and go-filecoin use unsigned 64-bit integers to represent sector ids, but the ["proofs primitive" operations](https://github.com/filecoin-project/rust-fil-proofs/blob/master/filecoin-proofs/src/api.rs#L184) in the `rust-proofs` crate expect 31-byte arrays. The [proofs portion of the specification](https://github.com/filecoin-project/specs/blob/master/proofs.md#seal) also uses a 31-byte array for the sector id parameter of `Seal`, `VerifySeal`, and `Unseal`.

The protocol section of the specification doesn't say anything about this type, and the `SectorSet` data structure (indexed by sector id) isn't specified either.

I think the path forward will be clear if the protocol portion of the specification tells us how to represent a sector id.

**Comment by whyrusleeping** [comment]
Ah yeah, the definition of the SectorID is missing. It should just be an integer. Technically up to 31 bytes long, but I think for all practical purposes we can just use a uint64 as we will never have a single miner with 2^64 sectors

**Comment by laser** [comment]
@whyrusleeping - I just [added an issue to the specs repo](https://github.com/filecoin-project/specs/issues/437) requesting specification of the SectorID type (and recommended a 64-bit, unsigned integer). Once that spec change has been ratified, I'll go forward with the change which you propose.

**Comment by laser** [comment]
@dignifiedquire - Have you confirmed with @nicola that we can change the Rust API to accept a `u64` instead of `[31]byte` for sector ID (and instead convert to a 31-byte array internally, within rust-fil-proofs)? I'd like to change all of this stuff in a single shot, if possible.

**Comment by laser** [comment]
This is [done](https://github.com/filecoin-project/go-sectorbuilder/blob/master/bindings.go#L105) [in `master`](https://github.com/filecoin-project/go-sectorbuilder/blob/master/bindings.go#L51).
